entrypoint: gunicorn -t 2400 -b :$PORT main:app
instance_class: F4_HIGHMEM
runtime: python37
service: explicit
env_variables:
  CLOUD_SQL_CONNECTION_NAME: gchgame:us-central1:gotchu
  DB_USER: neriasql
  DB_PASS: Neria123
  DB_NAME: responses
